spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ren
    username: postgres
    password: 4560
  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
logging:
  level:
    root:
      com:
        ren:
          orderingSystem: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG

springdoc:
  swagger-ui:
    url:  ${CLOUDFLARE_URL}/v3/api-docs
server:
  forward-headers-strategy: framework