spring:
  datasource:
    url: jdbc:postgresql://ep-tiny-mountain-aebogbpo-pooler.c-2.us-east-2.aws.neon.tech:5432/Ren
    username: neondb_owner
    password: ${NEON_DB_PASS}
  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
logging:
  level:
    root:
      com:
        ren:
          orderingSystem: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
        static: ${AWS_REGION}

aws:
  bucket:
    name: ${AWS_BUCKET_NAME}
springdoc:
  swagger-ui:
    url:  ${CLOUDFLARE_URL}/v3/api-docs
server:
  forward-headers-strategy: framework