spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ordering_system
    username: postgres
    password: password
  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-secret}
            scope: openid, email, profile
logging:
  level:
    root:
      com:
        ren:
          orderingSystem: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy}
      secret-key: ${AWS_SECRET_KEY:dummy}
    region:
        static: ${AWS_REGION:us-east-1}

aws:
  bucket:
    name: ${AWS_BUCKET_NAME:dummy-bucket}
springdoc:
  swagger-ui:
    url:  ${CLOUDFLARE_URL:http://localhost:8080}/v3/api-docs
server:
  forward-headers-strategy: framework